name: Java CI

on: [push]

jobs:
  build:
    runs-on: bq22-self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 11
          maven-version: 3.8.1
      - name: Verify maven dependecies
        run: mvn verify
      - name: Unit tests
        run: mvn test
      - name: Build
        run: mvn package
      - name: Display the path
        run: ls
        shell: bash
      - name: Display the path
        run: pwd
        shell: bash
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "*"
          target: "/var/www/med-clinica/"
