name: Java CI

on: [push]

jobs:
  build:
    runs-on: bq22-self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 11
          maven-version: 3.8.1
      - name: Verify maven dependecies
        run: mvn verify
      - name: Unit tests
        run: mvn test
      - name: Build
        run: mvn package
      - name: Copy artefact
        run: cp -r * /var/www/med-clinica
        shell: bash
      - name: Deploy application
        run: |
          cd /var/www/med-clinica
          docker-compose up -d
        shell: bash